name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          COMMIT_MESSAGE: "📊 Updated WakaTime stats automatically"
          SHOW_LINES_OF_CODE: "false"
          SHOW_LOC_CHART: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_SHORT_INFO: "false"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_TIMEZONE: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
          SHOW_TOTAL_CODE_TIME: "true"
